Controllers/PlanetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using App.Services;

namespace App.Controllers
{
   [Route("he-mat-troi/[action]")]
   public class PlanetController : Controller
   {
      private readonly PlanetService _planetService;
      private readonly ILogger<PlanetController> _logger;
      public PlanetController(PlanetService planetService, ILogger<PlanetController> logger)
      {
         _planetService = planetService;
         _logger = logger;
      }

      [Route("planets")]
      // nếu là /planets thì sẽ k kết hợp với he-mat-troi
      // khi đã thiết lập route ở controller thì phải thiết lập route ở action
      public IActionResult Index()
      {
         return View();
      }

      [BindProperty(SupportsGet = true, Name = "action")]
      public string Name { get; set; }

      [Route("[controller]/[action].html", Order = 1, Name = "mercury1")] // planet/mercury.html
      [Route("planet/[action]", Order = 2, Name = "mercury2")] // planet/mercury
      public IActionResult Mercury()
      {
         var planet = _planetService.GetPlanets().FirstOrDefault(p => p.Name == "Mercury");
         return View("Detail", planet);
      }

      [Route("planets/{id}")]
      // [HttpGet("")] 
      public IActionResult PlanetInfo(string id)
      {
         var planet = _planetService.GetPlanets().FirstOrDefault(p => p.Id == id);
         return View("Detail", planet);
      }
   }
}

Views/Shared/_AlertMessage.cshtml
@{
    var message = TempData["StatusMessage"] as string;
}
@if (!string.IsNullOrEmpty(message))
{
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    @message
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
}

Views/Shared/_CartPartial.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json

@inject CartService _cartService;


@{
    var cart = _cartService.GetCartItems();
    
    if (cart.Count > 0) {
        <div class="nav-item"><a class="text-warning" asp-route="cart"><i class="fas fa-shopping-cart"></i>(@cart.Count)</a></div>
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/App.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <script src="/_framework/aspnetcore-browser-refresh.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Blog" asp-controller="ViewPost" asp-action="Index">Blog</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Product" asp-controller="ViewProduct" asp-action="Index">Product</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet" asp-action="Index">Planet</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Contact" asp-controller="Contact" asp-action="SendContact">
                                <i class="fas fa-phone-alt"></i>
                                Contact
                            </a>
                        </li> 
                    </ul>
                </div>
                @await Html.PartialAsync("_CartPartial")
                <partial name="_LoginPartial" />
                <partial name="_MenuManagePartial" />
           
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Identity
@using App.Models
@using App.Menu;


@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/lib/jquery-easing/jquery.easing.min.js"></script>

   

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Home" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">AppMvc.Net</div>
            </a>


            @await RenderSectionAsync("Sidebar", false) 

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    
                   <h1>@ViewData["Title"]</h1>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
  
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                                    <i class="far fa-user"></i>
                                    @UserManager.GetUserName(User)!
                                </span>
                                


                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-controller="Manage" asp-action="Index" asp-area="Identity">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Hồ sơ
                                </a>
                               
                                <div class="dropdown-divider"></div>
                                <form asp-area="Identity" class="dropdown-item" asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
                                    <button title="Đăng xuất" type="submit" class="btn navbar-btn navbar-link">
                                        <i class="fas fa-sign-out-alt"></i> Đăng xuất 
                                    </button>
                                </form>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; AppMvc.Net 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->


        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_MenuManagePartial.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationService

@{
    var hasViewManageMenuPermission = (await authorizationService.AuthorizeAsync(User, "ViewManageMenu")).Succeeded;
}

@if (hasViewManageMenuPermission)
{
    <a class="nav-link" asp-action="Index" asp-controller="AdminCP" asp-area="AdminCP">
        <i class="fas fa-cog"></i>  Quản trị
    </a>
}

Views/Shared/_PagingXTL.cshtml
@* 
    Model:
      - currentPage:int - Trang hiện tại
      - countPages:int - tổng số trang
      - generateUrl:delegate Func<int?, string> trả về URL tương ứng với trang p (1,2,3 ...)
*@

@model App.Models.PagingModel
@{
    int currentPage  = Model.currentpage;
    int countPages   = Model.countpages;
    var generateUrl  = Model.generateUrl;


    
    if (currentPage > countPages) 
      currentPage = countPages;

    if (countPages <= 1) return;
    

    int? preview = null;
    int? next = null;

    if (currentPage > 1)
        preview = currentPage - 1;

    if (currentPage < countPages)
        next = currentPage + 1;

    // Các trang hiện thị trong điều hướng
    List<int> pagesRanges = new List<int>();    

        
    int delta      = 5;             // Số trang mở rộng về mỗi bên trang hiện tại     
    int remain     = delta * 2;     // Số trang hai bên trang hiện tại

    pagesRanges.Add(currentPage);
    // Các trang phát triển về hai bên trang hiện tại
    for (int i = 1; i <= delta; i++)
    {
        if (currentPage + i  <= countPages) {
            pagesRanges.Add(currentPage + i); 
            remain --;
        }
               
        if (currentPage - i >= 1) {
            pagesRanges.Insert(0, currentPage - i);
            remain --;
        }
            
    }    
    // Xử lý thêm vào các trang cho đủ remain 
    //(xảy ra ở đầu mút của khoảng trang không đủ trang chèn  vào)
    if (remain > 0) {
        if (pagesRanges[0] == 1) {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.Last() + 1 <= countPages) {
                    pagesRanges.Add(pagesRanges.Last() + 1);
                }
            }
        }
        else {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.First() - 1 > 1) {
                    pagesRanges.Insert(0, pagesRanges.First() - 1);
                }
            }
        }
    }

}

@* PHÁT SINH HTML*@

<ul class="pagination">
    <!-- Previous page link -->
    @if (preview != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(preview)">Trang trước</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang trước</a>
        </li>
    }
      
    <!-- Numbered page links -->
    @foreach (var pageitem in pagesRanges)
    {
        if (pageitem != currentPage) {
            <li class="page-item">
                <a class="page-link" href="@generateUrl(pageitem)">
                    @pageitem
                </a>
            </li>
        }   
        else 
        {
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">@pageitem <span class="sr-only">(current)</span></a>
            </li>
        }
    }


    <!-- Next page link -->
    @if (next != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(next)">Trang sau</a>
        </li>
    }
    else 
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang sau</a>
        </li>
    }
</ul>

Views/Shared/_StatusMessage.cshtml
@{
    var mgs = TempData["StatusMessage"] as string;
}

@if (!String.IsNullOrEmpty(mgs))
{
    var statusMessageClass = mgs.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @mgs
    </div>
}

Views/Shared/_Summernote.cshtml
@model App.Models.Summernote

@if (Model.LoadLibrary)
{
    <script src="~/lib/summernote/summernote-bs4.min.js"></script>
    <link rel="stylesheet" href="~/lib/summernote/summernote-bs4.min.css" />

    <link rel="stylesheet" href="~/lib/jqueryui/themes/base/theme.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/themes/base/jquery-ui.css" />
    <link rel="stylesheet" href="~/lib/elfinder/css/elfinder.full.css" />
    <link rel="stylesheet" href="~/lib/elfinder/css/theme.min.css" />
    
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/elfinder/js/elfinder.min.js"></script>       
}


<script>

   (function (factory) {
        if (typeof define === 'function' && define.amd) {
            define(['jquery'], factory);
        } 
        else if (typeof module === 'object' && module.exports) {
            module.exports = factory(require('jquery'));
        } else {
            factory(window.jQuery);
        }
    }(function ($) {
      $.extend($.summernote.plugins, {
            // Tạo plugin tên elfinder  
            'elfinder': function (context) {
                var self = this;
                // ui has renders to build ui elements.
                var ui = $.summernote.ui;
                // Tạo nút bấm
                context.memo('button.elfinder', function () {
                    var button = ui.button({
                        contents: '<i class="note-icon-picture"/> elFinder',
                        tooltip: 'Quản lý file',
                        click: function () {
                            // Bấm vào nút bấm gọi hàm elfinderDialog   
                            elfinderDialog(context); 
                        }
                    });
                    // create jQuery object from button instance.
                    var $elfinder = button.render();
                    return $elfinder;
                });
                // This methods will be called when editor is destroyed by $('..').summernote('destroy');
                // You should remove elements on `initialize`.
                this.destroy = function () {
                    this.$panel.remove();
                    this.$panel = null;
                };
            }
      
        });
    }));


    function elfinderDialog(editor) {
            var fm = $('<div/>').dialogelfinder({

            baseUrl: "@Url.Content("~/lib/elfinder/")",
            url: "@Url.Action("Connector", "FileManager", new {area = "Files"})",               

            lang : 'vi',
            width : 840,
            height: 450,
            destroyOnClose : true,
            getFileCallback : function(files, fm) {
                console.log(files);
                            editor.invoke('editor.insertImage', files.url);
            },
            commandsOptions : {
                getfile : {
                    oncomplete : 'close',
                    folders : false
                }
            }
        }).dialogelfinder('instance');
    }



    $(document).ready(function(){
        $('@Model.IDEditor').summernote({
            height: @Model.height,
            toolbar: @Html.Raw(Model.toolbar)
        });
    });  
</script>